// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Alfred Jean LLC

//! Centralized runtime environment variable access.
//!
//! All runtime env vars used by the CLI are defined and accessed through
//! this module. Constants are generated by `build.rs`.

use std::path::PathBuf;

/// Generated env var name constants.
pub mod names {
    include!(concat!(env!("OUT_DIR"), "/env_names.rs"));
}

/// Returns `true` if `NO_COLOR` is set to `"1"`.
///
/// Used by `should_colorize()` for the strict "1" check.
pub fn no_color() -> bool {
    std::env::var(names::NO_COLOR).is_ok_and(|v| v == "1")
}

/// Returns `true` if `NO_COLOR` is set to any value (including empty).
///
/// Per [no-color.org](https://no-color.org/), presence of `NO_COLOR`
/// with any value disables color.
pub fn no_color_set() -> bool {
    std::env::var_os(names::NO_COLOR).is_some()
}

/// Returns `true` if `COLOR` is set to `"1"`.
///
/// Used by `should_colorize()` to force colors.
pub fn force_color() -> bool {
    std::env::var(names::COLOR).is_ok_and(|v| v == "1")
}

/// Returns `true` if `COLOR` is set to any value.
///
/// Used by `resolve_color()` to force color output.
pub fn force_color_set() -> bool {
    std::env::var_os(names::COLOR).is_some()
}

/// Returns `true` if running in a known non-interactive / AI agent environment.
///
/// Checks for `CLAUDE_CODE`, `CODEX`, `CURSOR`, or `CI`.
pub fn is_non_interactive() -> bool {
    std::env::var_os(names::CLAUDE_CODE).is_some()
        || std::env::var_os(names::CODEX).is_some()
        || std::env::var_os(names::CURSOR).is_some()
        || std::env::var_os(names::CI).is_some()
}

/// Returns `true` if `QUENCH_DEBUG` is `"1"` or `"true"` (case-insensitive).
pub fn quench_debug() -> bool {
    std::env::var(names::QUENCH_DEBUG).is_ok_and(|v| v == "1" || v.eq_ignore_ascii_case("true"))
}

/// Returns `true` if `QUENCH_DEBUG_FILES` is `"1"` or `"true"` (case-insensitive).
pub fn quench_debug_files() -> bool {
    std::env::var(names::QUENCH_DEBUG_FILES)
        .is_ok_and(|v| v == "1" || v.eq_ignore_ascii_case("true"))
}

/// Returns the `QUENCH_LOG` env var name for use with `EnvFilter`.
pub fn quench_log_var() -> &'static str {
    names::QUENCH_LOG
}

/// Returns the user's home directory from `HOME`.
pub fn home() -> Option<PathBuf> {
    std::env::var_os(names::HOME).map(PathBuf::from)
}

/// Returns the XDG data home directory from `XDG_DATA_HOME`.
pub fn xdg_data_home() -> Option<PathBuf> {
    std::env::var_os(names::XDG_DATA_HOME).map(PathBuf::from)
}

/// Returns the XDG config home directory from `XDG_CONFIG_HOME`.
pub fn xdg_config_home() -> Option<PathBuf> {
    std::env::var_os(names::XDG_CONFIG_HOME).map(PathBuf::from)
}

#[cfg(test)]
#[path = "env_tests.rs"]
mod tests;
