#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alfred Jean LLC
# Generates an 800-line Rust file for testing cloc violations

cat << 'HEADER'
//! This file is intentionally oversized to trigger cloc violations.
//!
//! It contains more than 750 lines to exceed the default max_lines limit.
//! Generated by scripts/generate-oversized.sh

#![allow(dead_code)]

HEADER

# Generate 790 function definitions (one per line plus overhead = ~800 lines)
for i in $(seq -w 1 790); do
    echo "pub fn func_$i() -> i32 { $i }"
done

echo ""
echo "// End of generated file"
